version: '3.1'
services:
    tiassicuro-web-odoo-dev:
        image: odoo:18.0
        container_name: tiassicuro-web-odoo-dev
        depends_on:
            - tiassicuro-db-odoo-dev
        ports:
            - "8069:8069"
        volumes:
            - tiassicuro-web-odoo-data-dev:/var/lib/odoo
#            - ./odoo.conf:/etc/odoo/odoo.conf
            - ./addons:/mnt/extra-addons
        environment:
            HOST: tiassicuro-db-odoo-dev
            USER: ${ODOO_USER}
            PASSWORD: ${ODOO_PASSWORD}
    tiassicuro-db-odoo-dev:
        image: postgres:17
        container_name: tiassicuro-db-odoo-dev
        ports:
          - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
          - tiassicuro-db-postgres-data-dev:/var/lib/postgresql/data/pgdata
    tiassicuro-pgadmin-odoo-dev:
        image: dpage/pgadmin4
        container_name: tiassicuro-pgadmin-odoo-dev
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - tiassicuro-pgadmin-data-dev:/var/lib/pgadmin
volumes:
    tiassicuro-web-odoo-data-dev:
    tiassicuro-db-postgres-data-dev:
    tiassicuro-pgadmin-data-dev:
